/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

import java.sql.ResultSet;

/**
 *
 * @author Ahmad Hanafi
 */
public class SewaModel {
    private static DBHelper dbHelper;
    private static final String tableName = "tbl_travel_sewa";
    
    public static String idSewa;
    public static String noSewa;
    public static String tglSewa;
    public static String namaPenyewa;
    public static String kodeTravel;
    public static String jumlahSewa;
    public static String totalBayar;
    
    public SewaModel() {
        dbHelper = new DBHelper();
    }
    
    public void setValue(String nomor, String nama, String tgl, String kode, String jumlah, String total) {
        noSewa = nomor;
        tglSewa = tgl;
        namaPenyewa = nama;
        kodeTravel = kode;
        jumlahSewa = jumlah;
        totalBayar = total;
    }
    
    public boolean insertSewa() {
        String autoGeneratedCode = getAutoCode();
        String columns = "no_sewa, tgl_sewa, nm_penyewa, kode_travel, jumlah_sewa, total_bayar";
        String values = "'" + noSewa +"', ";
                values += "'" + tglSewa +"', ";
                values += "'" + namaPenyewa +"',";
                values += "'" + kodeTravel +"',";
                values += "'" + jumlahSewa +"',";
                values += "'" + totalBayar +"'";
        
        return dbHelper.Insert(tableName, columns, values);
    }
    
    public boolean updateSewa() {    
        String data = "tgl_sewa = '" + tglSewa + "', ";
        data += "kode_travel= '" + kodeTravel + "', ";
        data += "nm_penyewa = '" + namaPenyewa + "', ";
        data += "jumlah_sewa = '" + jumlahSewa + "', ";
        data += "total_bayar = '" + totalBayar + "'";
        
        String whereCondition = "no_sewa = '" + noSewa + "'";
        return dbHelper.Update(tableName, data, whereCondition);
    }
    
    public ResultSet getAllSewa() {
        return dbHelper.GetData(tableName);
    }
    
    public ResultSet getSewaWithTravel() {
        String sewaTable = tableName + "_2017102020";
        String travelTable = "tbl_travel_2017102020";
        String SqlJoin = "SELECT * FROM "+sewaTable+" JOIN "+travelTable+" USING (kode_travel)";
        return dbHelper.GetDataWithCutomQuery(SqlJoin);
    }
    
    public ResultSet getSewaByNomor(String kode) {
        return dbHelper.GetDataBy(tableName, "no_sewa", kode);
    }
    
    public void deleteSewa(String noSewa) {
        dbHelper.Delete(tableName, "no_sewa = '" + noSewa + "'");
    }
    
    public String getAutoCode() {
        return dbHelper.generateCode(tableName, "no_sewa", "SWA");
    }
    
    public ResultSet getSewaBelumKembali() {
        String sewaTable = tableName + "_2017102020";
        String pengembalianTable = "tbl_travel_kembali_2017102020";
        String subQuerySql = "SELECT * FROM "+sewaTable+" WHERE no_sewa NOT IN (";
        subQuerySql += "SELECT no_sewa FROM "+ pengembalianTable +")";
        return dbHelper.GetDataWithCutomQuery(subQuerySql);
    }
    
    public ResultSet getSearch(String val) {
        return dbHelper.GetSearchData(tableName, "no_sewa, nm_penyewa, kode_travel", val);
    }
    
    public ResultSet getFilterData(String start, String end) {
        return dbHelper.GetDataFilterByDate(tableName, "tgl_sewa", start, end);
    }
}
