/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

import java.sql.ResultSet;

/**
 *
 * @author Ahmad Hanafi
 */
public class TravelModel {
    private static DBHelper dbHelper;
    private static final String tableName = "tbl_travel";
    
    public static String kodeTravel;
    public static String namaTravel;
    public static String hargaTravel;
    public static String jumlahTravel;
    public static String keterangan;
    
    public TravelModel() {
        dbHelper = new DBHelper();
    }
    
    public void setValue(String kode, String nama, String harga, String jumlah, String ket) {
        kodeTravel = kode;
        namaTravel = nama;
        hargaTravel = harga;
        jumlahTravel = jumlah;
        keterangan = ket;
    }
    
    public void setUpdateValue(String uname, String nama, String kode_travel) {
        namaTravel = uname;
        jumlahTravel = nama;
        kodeTravel = kode_travel;
    }
    
    public boolean insertTravel() {
        String autoGeneratedCode = getAutoCode();
        String columns = "kode_travel, nm_travel, harga, jumlah_travel, keterangan";
        String values = "'"+ autoGeneratedCode +"', ";
                values += "'" + namaTravel +"', ";
                values += "'" + hargaTravel +"',";
                values += "'" + jumlahTravel +"',";
                values += "'" + keterangan +"'";
        
        return dbHelper.Insert(tableName, columns, values);
    }
    
    public boolean updateTravel() {    
        String data = "nm_travel = '" + namaTravel + "', ";
        data += "jumlah_travel= '" + jumlahTravel + "', ";
        data += "harga = '" + hargaTravel + "', ";
        data += "keterangan = '" + keterangan + "'";
        
        String whereCondition = "kode_travel = '" + kodeTravel + "'";
        return dbHelper.Update(tableName, data, whereCondition);
    }
    
    public boolean updateJumlahTravel(String kode, String jumlah, String operasi) {
        String whereCondition = "kode_travel = '" + kode + "'";
        String data = "jumlah_travel = jumlah_travel" + operasi +jumlah+"";
        return dbHelper.Update(tableName, data, whereCondition);
    }
    
    public ResultSet getAllTravel() {
        return dbHelper.GetData(tableName);
    }
    
    public ResultSet getTravelByCode(String kode) {
        return dbHelper.GetDataBy(tableName, "kode_travel", kode);
    }
    
    public void deleteTravel(String kode) {
        dbHelper.Delete(tableName, "kode_travel = '" + kode + "'");
    }
    
    public String getAutoCode() {
        return dbHelper.generateCode(tableName, "kode_travel", "TRV");
    }
    
    public ResultSet getSearch(String val) {
        return dbHelper.GetSearchData(tableName, "kode_travel, nm_travel, keterangan", val);
    }
}
