/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

import java.sql.ResultSet;

/**
 *
 * @author Ahmad Hanafi
 */
public class UserModel {
    private static DBHelper dbHelper;
    private static String tableName = "tbl_user";
    
    public static String userId;
    public static String username;
    public static String password;
    public static String namaLengkap;
    
    public UserModel() {
        dbHelper = new DBHelper();
    }
    
    public void setValue(String uname, String pass, String nama) {
        username = uname;
        password = pass;
        namaLengkap = nama;
    }
    
    public void setUpdateValue(String uname, String nama, String id_user) {
        username = uname;
        namaLengkap = nama;
        userId = id_user;
    }
    
    public boolean insertUser() {
        String autoGeneratedCode = getAutoCode();
        String columns = "id_user, username, password, nm_user";
        String values = "'"+ autoGeneratedCode +"', ";
                values += "'" + username +"', ";
                values += "MD5('" + password +"'),";
                values += "'" + namaLengkap +"'";
        
        return dbHelper.Insert(tableName, columns, values);
    }
    
    public boolean updateUser() {    
        String data = "username = '" + username + "', ";
        data += "nm_user= '" + namaLengkap + "' ";
        
        String whereCondition = "id_user = '" + userId + "'";
        return dbHelper.Update(tableName, data, whereCondition);
    }
    
    public ResultSet loadData() {
        return dbHelper.GetData(tableName);
    }
    
    public ResultSet getUserById(String userId) {
        return dbHelper.GetDataBy(tableName, "id_user", userId);
    }
    
    public void deleteUser(String userId) {
        dbHelper.Delete(tableName, "id_user = '" + userId + "'");
    }
    
    public String getAutoCode() {
        return dbHelper.generateCode(tableName, "id_user", "USR");
    }
}
